bcgov/common-hosted-email-service

- app/app.js
- app/config/custom-environment-variables.json
- app/config/default.json
- openshift/README.md
This PR allows POST body content to be up to 100mb in size.
This overrides the default 100kb body size limit. As we are encoding our files into base64, this limit is quickly exceeded.
As of `express` 4.16.0, the `body-parser` library is not needed as it is reincluded with the base distribution of express.
Ref: https://stackoverflow.com/a/43626891
> Allow JSON Body requests up to 100mb

- app/src/components/merge.js
This PR is needed in order to ensure that merge endpoint is yielding correct array of object format, not a list of strings.
> Hotfix: Ensure merge endpoint returns msgId wrapped in an object

- app/src/components/merge.js
- app/src/components/status.js
- app/src/components/utils.js
- app/src/docs/v1.api-spec.yaml
- app/src/routes/v1/email.js
- app/tests/unit/components/merge.spec.js
- app/tests/unit/components/status.spec.js
- app/tests/unit/components/utils.spec.js
- app/tests/unit/routes/v1/email.spec.js
This PR implements delayTS support in the API by exposing the delay support from Bull Queue.
Other enhancements:
* Add tag attribute to /email and /emailMerge endpoint responses
This PR will enable users to be able to delay sending email messages until a specified time (implemented via UTC unix time).
[[SHOWCASE-250]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-250)
> Add and expose delayTS support to API

- Jenkinsfile.cicd
- openshift/redis-ephemeral.dc.yaml
This PR modifies the Redis deployment to leverage an explicit PersistentVolumeClaim.
The PVC is required in order to ensure that we do not have data loss when the Redis pod exits.
[[SHOWCASE-284]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-284)
> Change Redis Deployment to be backed by a PVC

- Jenkinsfile
- Jenkinsfile.cicd
- app/app.js
- app/config/custom-environment-variables.json
- app/config/default.json
- app/config/test.json
- app/package-lock.json
- app/package.json
- openshift/app.dc.yaml
- openshift/patroni-ephemeral.dc.yaml
- openshift/patroni.dc.yaml
- openshift/patroni.secret.yaml
- openshift/redis-ephemeral.dc.yaml
- openshift/redis.dc.yaml
This is an infrastructure change which introduces High Availability Postgres with the use of Patroni.
* Streamline Openshift deployments to skip re-deploying Redis and Patroni if they already exist
* Decouple Redis service from having the application name bound to it
* Add postgres database connection check to application on startup
In order to have some degree of reliable persistence, our team has decided that Postgres is the path forwards. This PR is a necessary backend infrastructure step to achieve that goal.
[[SHOWCASE-313]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-313)
> Add High Availability Postgres infrastructure support via Patroni

- app/package.json
- app/src/components/transformer.js
- app/src/components/utils.js
- app/src/components/validators.js
- app/src/docs/v1.api-spec.yaml
- app/src/middleware/validation.js
- app/src/routes/v1/email.js
- app/src/routes/v1/merge.js
- app/src/routes/v1/status.js
- app/src/services/chesSvc.js
- app/src/services/dataSvc.js
- app/src/services/emailSvc.js
- app/src/services/transform.js
- app/tests/integration/chesSvc.spec.js
- app/tests/unit/components/health.spec.js
- app/tests/unit/components/transformer.spec.js
- app/tests/unit/components/utils.spec.js
- app/tests/unit/components/validators.spec.js
- app/tests/unit/routes/v1/email.spec.js
- app/tests/unit/routes/v1/merge.spec.js
- app/tests/unit/routes/v1/status.spec.js
This PR implements the /status queryable endpoint as specified in the specification. 
- Adds missing 422 validation support to the /status endpoint family
- Improve unit test code structure for mocking classes
- Refactor transformer into a component
- Refactor validators into model and validator functions
[[SHOWCASE-326]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-326)
> Add Status Query endpoint support

- app/src/services/dataSvc.js
This bugfix ensures that the /status endpoint actually returns values for createdTS, delayTS and updatedTS instead of null.
> Bugfix non-default columns were not being returned for status query

- app/bin/www
- app/src/components/validators.js
- app/src/docs/v1.api-spec.yaml
- app/src/middleware/validation.js
- app/src/routes/v1/cancel.js
- app/src/services/chesSvc.js
- app/src/services/dataSvc.js
- app/src/services/queueSvc.js
- app/src/services/statisticSvc.js
- app/tests/integration/chesSvc.spec.js
- app/tests/unit/components/validators.spec.js
- app/tests/unit/routes/v1/cancel.spec.js
- app/tests/unit/routes/v1/merge.spec.js
- app/tests/unit/routes/v1/status.spec.js
This PR introduces queryable message cancel functionality to CHES.
* Add Content-Location header support to responses
* Update unit test to reduce redundant declarations
* Ensure test environment cleans up after each test appropriately
* Add validation enforcement on valid status state strings
This is needed in order to finish version 1 implementation of the CHES API as originally designed.
[[SHOWCASE-344]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-344)
> Add /cancel query support to API

- Jenkinsfile
- Jenkinsfile.cicd
If this is not done, existing patroni and redis instances will not be updated and redeployed.
NSPs never came into effect as it was skipped.
> Force Patroni and Redis to reapply deployment configs every time

- openshift/redis-ephemeral.dc.yaml
- openshift/redis.dc.yaml
This PR attempts to ensure that when Redis is not running, Openshift will restart the container correctly.
We want to avoid the situation where Redis has exited, but the container doesn't terminate and hangs in limbo instead.
[SHOWCASE-755](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-755)
Test this on Openshift by opening a terminal on redis-pr-39 container and then executing `kill -15 1`. This sends a SIGTERM to the init process (which is running Redis) and tells the application to kill itself. If this is working correctly, container should back-off and restart again shortly. Previously, a SIGTERM would happen, but the container would never clean up.
> Change redis liveness probe to use redis-cli

- openshift/patroni.dc.yaml
Since the platform needs to change from GlusterFS to netapp, we need to migrate our existing PVCs to the new system.
This is needed as GlusterFS is deprecated and will disappear at some point in the future.
[SHOWCASE-795](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-795)
Migration work has been done out of band. This PR is to ensure subsequent Patroni deployments remain in alignment with what is deployed.
> Change Patroni default storage class to netapp-block-standard

- openshift/redis.dc.yaml
Since the platform needs to change from GlusterFS to netapp, we need to migrate our existing PVCs to the new system.
This is needed as GlusterFS is deprecated and will disappear at some point in the future.
[SHOWCASE-797](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-797)
Migration work has been done out of band. This PR is to ensure subsequent Redis deployments remain in alignment with what is deployed.
> Change Redis default storage class to netapp-file-standard

- app/lcov-fix.js
- app/package-lock.json
- app/package.json
Preparing for imminent Vue update that will require a bump in Jest.  We know that Jest 25 is not delivering the lcov file to Sonarqube.  This PR is to address Jest 25 and Sonarqube not working.
Change is required because Jest 25 doesn't set lcov paths correctly.
Unit tests pass, but Coverage not passed to Sonarqube due to lcov path errors.
> Sonarqube with Jest 25

- app/src/components/utils.js
- app/tests/unit/components/utils.spec.js
- app/tests/unit/components/validators.spec.js
Should be handled and treated the same as undefined or 0.
Issue was a utility function didn't handle null.  The actual delay was fine and handled like 0.
The utility function is only called in one place, so toss up of where to put the fix.
[SHOWCASE-1332](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1332)
> When delayTS is explicitly set to null, it borks the delivery.

- app/package-lock.json
- app/package.json
- app/src/services/dataSvc.js
- app/tests/integration/chesSvc.spec.js
- app/tests/integration/dataSvc.spec.js
- app/tests/integration/statisticSvc.spec.js
This PR updates all outdated npm packages and libraries to resolve any potentially remaining security vulnerabilities.
**Other changes:**
- Refactor uuid library invocation signature
- Change scripts to invoke via relative node_modules
[SHOWCASE-502](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-502)
Objection has been upgraded from 1.6.11 to 2.2.2. A set of methods have been marked as deprecated and will need to be rewritten at some point before Objection 3.x comes out:
```
`QueryBuilder#eagerAlgorithm` method is deprecated. You should explicitly use either withGraphFetched or withGraphJoined methods. `eagerAlgoritm` method will be removed in 3.0
`QueryBuilder#eager` method is deprecated. You should use the `withGraphFetched` …
```
> Mass npm package updates

- app/src/services/dataConn.js
This PR makes it so that the periodic DB connection checks if the DB is Postgres, whether DB is queryable, and if DB is not in read-only mode.
As our DB is managed by Patroni for High Availability, there may be rare edge cases where CHES may retain a connection to a non-master node of Postgres. When this happens, any transactions needing to write to the database will fail because it is connected to a read-only instance. We want the container to fail fast and exit out so that it can be restored in a new pod connecting to the right DB instance as soon as the read-only state is detected.
[SHOWCASE-1478](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1478)
Inspiration from following SO thread: https://stackoverflow.com/a/9277406
> Change DB Connection probe to detect read-only state

- app/src/services/dataSvc.js
After merging this will do further confirmation in TEST env before prod deployment.
Long investigation, tiny change.
Prod CHES has been getting progressively slower on message POST as the database gets fuller. Traced the database heaviness to the readTransaction call to return transaction detail.
It joins the statuses for the messages, but does a sort on the inner query that a join is being done on, causing query plan complexity that weighs a lot when status has many records (like on prod).
This sort isn't necessary for posting the message (or posting a merge of many messages), and this readTransaction call is only being done on those 2 posts (**the status endpoints use different queries**), so it's safe to move it out of the inner query after testing.
See further comments below for …
> Modify read transaction query

- README.md
- app/package-lock.json
- app/src/components/transformer.js
- app/src/docs/v1.api-spec.yaml
- app/tests/unit/components/transformer.spec.js
Add the smtp response to the Status calls to facilitate troubleshooting.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1151
This field is public.message.sendResult in the DB and is populated when the message is set to completed.
Since this is an additive change to a status endpoint I don't think we need to worry about any API versioning on this change.
Leaving draft. If reviews look good will set up some test data before merge on monday.
Add badge (#62) and `npm audit fix` as well
> Return SMTP response in status

- app/config/custom-environment-variables.json
- app/src/components/keycloak.js
- openshift/README.md
- Backend behaves statelessly for JWT verification when realmPublicKey is supplied
- Without realmPublicKey, backend must call OIDC endpoint first
> Add sso public key to app cache

- app/app.js
- app/src/services/dataConn.js
- app/src/services/queueConn.js
- Attempt to refresh DB pool connections when a 500 error occurs
- Change ioredis events to verbose
- Make QueueConnection.close non-static
- Ensure queue and data connections actually close before quitting
[SHOWCASE-2010](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2010)
> Attempt to refresh DB pool connections on 500 error

- app/src/services/emailConn.js
- openshift/app.dc.yaml
- Set CPU limit back to 250m
- Set SMTP connection timeout to 5 minutes to match Microsoft Exchange server defaults ([Ref](https://docs.microsoft.com/en-us/exchange/mail-flow/message-rate-limits?view=exchserver-2019#message-throttling-on-receive-connectors))
> CPU Limit increase and SMTP Pool timeout reduction

- app/app.js
- Only reset DB connections if it is a 5xx class error
[SHOWCASE-2075](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2075)
> Bugfix: Only reset DB connections if it is a 5xx class error

- app/package-lock.json
- app/package.json
This PR rolls back Bull Queue to before 4.0.0 with the enforced breaking change. For some reason, it will not take on Cluster mode.
[SHOWCASE-2288](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2288)
Potentially related issue: https://github.com/OptimalBits/bull/issues/2186
> Rollback bull queue to 3.29.3

- app/src/middleware/authorizedParty.js
This PR ensures that the middleware should only attempt to parse azp from JWT token if it actually exists. (We don't want kube-probe error spam)
[SHOWCASE-2288](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2288)
> Bugfix: Only attempt to parse azp from JWT token if it actually exists

- openshift/app.bc.yaml
This PR addresses an operational issue where the `/.npm` root cache has problems being accessed by npm which is now preventing new pods from spinning up on Openshift. Also bumps Node from 16 to 20 LTS.
> Update Node to 20.9.0 LTS and bugfix npm eacces error

- .github/CODEOWNERS
- .github/actions/build-push-container/action.yaml
- .github/actions/deploy-to-environment/action.yaml
- .github/workflows/codeql-analysis.yaml
- .github/workflows/on-pr-opened.yaml
- .github/workflows/on-push.yaml
- .github/workflows/unit-tests.yaml
- Dockerfile
This PR focuses on implementing a parallel Github Actions based image builder. While the old Jenkins pipeline depends on the image built by the buildconfig, we will be transitioning away from using that and instead storing our container artifacts in ghcr.io. This also updates our unit testing GA to test on Node 16, 18 and 20.
- 8a0a5c3 Implement GHCR container image build pipeline
- fc2c1b8 Extract Dockerfile from BuildConfig template
[SHOWCASE-2755](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2755)
> Implement GHCR container image build pipeline

- .github/CODEOWNERS
- app/src/services/migrations/20240229000000_cascade.js
This QoL change ensures that referential integrity in the database is preserved in the event records are removed from the database.
[SHOWCASE-2625](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2625)
> Modify foreign key constraint triggers to cascade
