Jenkinsfile
Jenkinsfile.cicd
app/app.js
app/config/custom-environment-variables.json
app/config/default.json
app/config/test.json
app/package-lock.json
app/package.json
app/src/components/email.js
app/src/components/keycloak.js
app/src/docs/v1.api-spec.yaml
app/src/routes/v1.js
app/src/routes/v1/checks.js
app/src/routes/v1/email.js
app/tests/unit/routes/v1/checks.spec.js
app/tests/unit/routes/v1/email.spec.js
openshift/README.md
openshift/app.dc.yaml

This PR implements Keycloak JWT authentication on the `checks` and `email` endpoints.
This is necessary because... well... security.
Other notable changes included in this PR include:
* Gzip compression support
* Minor problem/error refactor for better error cascade handling
* API spec inconsistencies fixed
[[SHOWCASE-239]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-239)
Breaking change (fix or feature that would cause existing functionality to change)

Add Keycloak JWT authentication

---

app/README.md
app/package-lock.json
app/package.json
app/src/docs/v1.api-spec.yaml

This PR adds API Usage documentation targeted for developers who wish to use this API. It details the general template capabilities of the email merge endpoint and what to expect from output, as well as references to the Nunjucks documentation.
Dependencies have also been updated.
[SHOWCASE-244](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-244)

Add API Usage documentation

---

app/src/components/email.js
app/src/components/utils.js
app/src/docs/v1.api-spec.yaml
app/src/routes/v1/email.js
app/tests/unit/components/email.spec.js
app/tests/unit/components/utils.spec.js

Add CC and BCC fields to the mail merge in the same way as "to" is handled (per context)

Add cc and bcc fields

---

.github/pull_request_template.md

This PR adds a checklist to the Pull Request template to ensure t hat the 
We want to ensure that all API changes are reflected correctly and correspond with what is implemented or desired.
[[SHOWCASE-149]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-149)

Add PR checklist for OAS 3.0 spec documentation updates

---

app/src/docs/v1.api-spec.yaml

This PR is a Request For Comment on  the significant changes on the Draft V1 API endpoints for CHES.
This allows us to have the flexibility to grow the API and satisfy incoming business needs and makes it less likely we will need to introduce a breaking change to the spec.
[[SHOWCASE-271]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-271)
ReDoc Quick Link: <https://ches-pr-11-9f0fbe-dev.pathfinder.gov.bc.ca/api/v1/docs>

Update CHES V1 API Specification

---

app/app.js
app/package-lock.json
app/src/components/checks.js
app/src/components/validators.js
app/src/middleware/validation.js
app/tests/unit/components/queue.spec.js
app/tests/unit/components/validators.spec.js

Add validation for delayTS.
Run all code through formatter.

Add validation for delayTS.

---

app/src/components/validators.js
app/src/docs/v1.api-spec.yaml
app/tests/unit/components/validators.spec.js

Changes in validation of contexts.

---

app/app.js
app/knexfile.js
app/package-lock.json
app/package.json
app/src/components/state.js
app/src/components/transformer.js
app/src/components/validators.js
app/src/docs/v1.api-spec.yaml
app/src/middleware/validation.js
app/src/routes/v1.js
app/src/routes/v1/cancel.js
app/src/routes/v1/email.js
app/src/routes/v1/health.js
app/src/routes/v1/status.js
app/src/services/chesSvc.js
app/src/services/dataSvc.js
app/src/services/queueConn.js
app/src/services/queueListener.js
app/src/services/queueSvc.js
app/tests/integration/chesSvc.spec.js
app/tests/integration/dataSvc.spec.js
app/tests/integration/dataUtils.js
app/tests/integration/statisticSvc.spec.js
app/tests/unit/components/state.spec.js
app/tests/unit/components/validators.spec.js
app/tests/unit/routes/v1.spec.js
app/tests/unit/routes/v1/cancel.spec.js

This PR introduces singular message cancel functionality to CHES.
* Update dependencies
* Add explicit status and queue enumerations
* Add 409 Conflict to API definition
* Update integration tests to cover status and cancel functionality
[[SHOWCASE-335]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-335)
[[SHOWCASE-345]](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-345)
* If you run the integration tests, you may see an ECONNRESET error show up at the end. This does not affect the tests or the environment and is simply due to Jest abruptly killing off the Redis connection.
* Any older versions of CHES may contain non-enumerated statuses and queue …

Add /cancel/:msgId support to API

---

app/README.md
app/package-lock.json
app/package.json

https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-370
Updating readme for npm dependencies which were out of date.
Update actual dependencies themselves as well to latest.
New feature (non-breaking change which adds functionality) 

Update dependencies in readme

---

README.md
app/README.md
app/package-lock.json
app/package.json

supports; <https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-810>
Make the application readme easier to navigate. 
Include a link to the API docs

edited readme

---

app/package-lock.json

This update to dot-prop npm package addresses a security vulnerability as reported here:
https://hackerone.com/reports/719856

upgrade dot-prop to version 5.1.1 or later

---

app/tests/postman/example.postman_environment.json

simplified example environment file

---

openshift/patroni-ephemeral.dc.yaml
openshift/patroni.dc.yaml

* Raise memory limits of persistent patroni
* Lower cpu limit of ephemeral patroni

Adjust Patroni resource utilization footprint

---

openshift/OIDC-Migration.md
openshift/README.md
openshift/app-oidc.dc.yaml
openshift/app.dc.yaml
openshift/nsp.yaml
openshift/patroni-ephemeral.dc.yaml
openshift/patroni.dc.yaml
openshift/redis-ephemeral.dc.yaml
openshift/redis.dc.yaml

This PR adds pre-emptive OCP4 changes, and provides templates and a plan of action for SSO to OIDC auth migration.
[SHOWCASE-1684](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1684)
Related to https://github.com/bcgov/common-document-generation-service/pull/47

Create Parallel OIDC version of CHES deployment

---

openshift/fluent-bit.cm.yaml

this change helps achieve log message checking/alerting for logs that arent in the expected apache format.
for example, if the message is 'ERR! Error doing something..'
We can modify the format of the logs collected by the sidecar to include the full original message in a field with key 'log'.. as well as the message parsed into apache format.

sidecar log format

---

app/src/middleware/mailApiTracker.js
app/src/services/chesSvc.js
app/src/services/dataSvc.js
app/src/services/emailSvc.js
app/src/services/queueConn.js
app/src/services/queueListener.js
app/src/services/queueSvc.js
app/src/services/statisticSvc.js
openshift/app.dc.yaml

This PR does the following:
- Make sure we immedately 500 report in response if email wasn't able to be queued into Redis
- Lower CPU resource limit based on load test observations
- Rethrow error to ensure the listener worker knows that sending failed
- Update log messages to specify what service class they came from
- Drop redundant redis error event handler
[SHOWCASE-1950](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1950)

Reliability Hardening

---

app/src/services/queueSvc.js

We are hoping to hard fail if it doesn't get into the queue instead of recording into DB with no Redis record

Reverse order of operations in enqueue task

---

app/app.js
app/src/services/chesSvc.js
openshift/app.hpa.yaml

This PR does the following:
- Force 503 response when app is not yet ready and mounted
- Avoids executing code while connections and stackpole are still loading
- On OCP, should prevent network traffic reaching pod while still loading
- Unblock enqueue action from accepted state
- We want express to be responsive - waiting on enqueue could block main event loop
- This will respond that their request was accepted immediately
- Add non-templated Horizontal Pod Autoscaler resource
[SHOWCASE-1950](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1950)
[SHOWCASE-1980](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-1980)

Improve API Availability

---

app/src/services/queueConn.js

- Refactor queue connection check to use ioredis ping/pong directly
- Hopefully this allows for detecting when Redis connections fails

Redis Stability Fixes

---

app/src/services/emailConn.js
app/src/services/emailSvc.js

- Reconfigure nodemailer to timeout failed connections after 10 seconds
- Leverage a pooled SMTP to reduce TCP network churn

Reconfigure nodemailer to timeout failed connections after 10 seconds

---

app/src/services/emailConn.js

Fix typos in SMTP connection pool handling

---

app/src/services/emailConn.js

Drop idle timeout to 30 seconds

---

app/app.js
app/src/services/emailConn.js

- Apply singleton pattern to nodemailer in EmailConnection class
- Only attempt to reset DB connections if not shutting down
- Report HTTP 503 when application is shutting down instead of 500
[SHOWCASE-2017](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2017)

Singleton Nodemailer enforcement

---

app/src/services/emailConn.js

- Ensure non-pooled SMTP connection attempts also terminate after 10 seconds
- [xI have added necessary documentation (if appropriate)

Ensure non-pooled SMTP connection attempts also terminate after 10 seconds

---

app/app.js
app/src/services/dataConn.js
app/src/services/emailConn.js
app/src/services/queueConn.js
openshift/app.dc.yaml

- Add optional callback support to close() connection methods
- Ensure synchronous shutdown cleanup occurs when exiting
- Ensure health probe is explicitly unregistered
- Extract anonymous cleanup function into explicit declaration
- Ensure cleanup doesn't get invoked twice
- Skip logging kube-probe requests
- Drop readiness probe failure tolerance
- We want to stop forwarding traffic to a potentially busy/failed pod immediately
[SHOWCASE-2025](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2025)

Graceful Shutdown Support

---

app/app.js
app/package-lock.json
app/package.json
app/tests/unit/components/utils.spec.js
app/tests/unit/routes/v1/health.spec.js

- Extend shutdown wait time to 5 seconds
- Hopefully this reduces statistical likelihood of service forwarding traffic to this pod
- Routine npm dependency updates
- Minor unit test error cleanup
[SHOWCASE-2099](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2099)

Extend shutdown wait time to 5 seconds

---

app/src/services/migrations/20220203173736_remove-stats.js

Adds migration file to remove the statistic table as it is no longer in use.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-2073

Add migration file to remove statistic table

---

app/config/custom-environment-variables.json
app/config/default.json
app/src/components/validators.js
app/tests/unit/components/validators.spec.js

Implements a config option to block donotreply/noreply emails or variants of.

Add config option to block donotreply and noreply senders

---

app/config/custom-environment-variables.json
app/src/components/validators.js
app/tests/unit/components/validators.spec.js

Adds an optional check to see if it the sender is from a BC Gov domain.
Combines the do not reply validation with this into a single function.

Add optional check for a BC Gov sender

---

app/src/components/keycloak.js
app/src/docs/v1.api-spec.yaml
app/src/routes/v1.js

All our clients have this EMAILER role so it is redundant.
We have Audience verification for client access.

Remove requirement for keycloak role EMAILER

---

openshift/patroni-ephemeral.dc.yaml
openshift/patroni.dc.yaml

Openshift Operational changes and minor triage fixes.
- 259b991 Switch to artifactory image source and reduce cpu request to 20m
- 94dd498 Allow privilege escalation for legacy operation context

Openshift 4.11 Fixes

---

app/config/default.json
app/config/test.json

Changed default keycloak realm from configuration.
This was some tidy up as a consequence of moving to a new realm for our hosted CHES client credentials flow.

Keycloak config change

---

openshift/app.dc.yaml

This improves security by being more explicit with what traffic is to be accepted from the Openshift Ingress.
[SHOWCASE-3447](https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3447)

Add explicit Network Policy for Openshift Ingress

---

app/app.js
app/src/routes/v1/cancel.js
app/src/routes/v1/status.js
app/src/services/dataConn.js
app/src/services/emailConn.js
app/src/services/queueConn.js
app/src/services/queueListener.js

This PR forces uuid arguments to be lower case before entering the service layer. This ensures that upper cased uuids can also be handled appropriately as intended. This PR also resolves an errant application condition where the application does not perform a hard exit when it is unable to acquire a queue connection on startup.
The onFailure error handler ensures that in the unlikely event the application is unable to perform standard status updates that it does not create an unhandledRejection that cascades to the main application event loop. If the log message is reached, data integrity must be checked as there is very likely an inconsistency between Redis and the DB that is not resolvable during normal runtime.
- a329d79 Add error handler to onFailure handler
- 3b2f74d Force uuid …

Make uuid handling case-insensitive and add error handler to onFailure handler

---

app/src/docs/v1.api-spec.yaml
app/src/middleware/authentication.js

Verify  audience on auth
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3500

Verify  audience on auth

---

app/src/docs/v1.api-spec.yaml

Update authentication url in the docs

---

openshift/app.dc.yaml

As title.
Part of regular updates to our supporting appliances.
https://apps.nrs.gov.bc.ca/int/jira/browse/SHOWCASE-3628

Update fluentbit image from 2.1.10 to 3.1.9

---

charts/ches/README.md

re-generate helm chart documentation

update helm docs

---

.github/actions/deploy-to-environment/action.yaml

part of our stack/pipeline upgrade.
- create temporary route for parallel deployment

temp route for migration

---

.github/environments/values.dev.yaml
.github/environments/values.prod.yaml
.github/environments/values.test.yaml
charts/ches/Chart.yaml
charts/ches/values.yaml

change pvc sizes

---

.github/environments/values.prod.yaml

increase size of pg backup repo1

increase size of pg backup repo1
